# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "SWNKkMY3R0YTQ2oWsvoFVZ1aw6S8fje3op7Y4Uy+hBhB8t1jtWKgDVd352k33glH/dO5EyG51dsDsldsbxXJ4dyd+nz3p8zGRbu+icbKc5feuQ4MG/VfYpV7xy/JknmmeLPzolVtiA/kHJlLx4eQ/xUUlZJKfYijonWvg594c1ZgVnfNKTRTP6HCSW3TQr+/Y8gYsua9OWyAsgMM1jIOjd925GJ2WymCfBQJ7lEfnnkjt0HuNLcwXVYZgF0aSRy1BvLYJpoHX5fozoP+ugHRGFNQcM7r1yFPPEkF/c634at300dVyyQm9S31/UTRwhImg0n5jx5iehv9WHeUgTsLdEtZvrK+vnJZPyy91DZZKJ+QnLUbk5OBVMPs+GKzJ/f0QWSPNk/QDimOZh27dVfNIQPb1uTURIjqqm18u5+ehLpkJsTnrRtO1elP/mUyX50WTZoAu0dLrXjHQoXicChfH51HdOCvwVMDXxRAiLZ943apCPoTBIor6/ARJRe8NcJuuAUzWNmDXeEC3KvyxljhFhnVz5hI3knGXGMGyx99BaTEZzjBzBT15M+aTzBjwCZtLTkSkE+vN9OCtk2RVxsYZ6EH1DOgL8zeIAc/ySZZh7vE88rqxc1Yfdp2yBiWqxi0KjBvQlQml7Sr45kMbeTPOm5ntkzyQmw0fAvBZIObiK0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
