travis:
  secure:
    BINSTAR_TOKEN: etSyp4Uc/+t3ZUPfHL/3sdCwyx3to3v1wxPOXybsx6fHVz9WG7u6SSXY+/2nXaMGK+WQRRLLkMVC7fwAwWbYBd85BOjZ1PkndjBcyPM48MeUIw3cLQoNP2eRg00xWZu6jsAAXgFJkvhG4iciL4zyTxAZvAekf21crLX3O+eGPNZKOuvy6Ri9N/q6degLcmJQxYYHYPkDEj8Yel6hQ4OFJniXBh2xqBwn7A1XLHNOds21MCMXdbs8+rJtd5LLNBFRrGRxq/Rz5rGOUMQYjSIPUWdIE8cbpRtGZqyXXwboKbQFDSX8lhPS7wPeXhRF3IagiR5ir8ZxkpWI4GXUHrnJN6iSXW8OmsFdaA0UPow9QfAzePCbfJvl4iVi6HpOBa/jHDG4azqwqRqL/tI+XpnobeW6n2CZpzaZN84w7xBRyQ+CK0FVUb5VfEXf1c25C9BUUbEzVJyEBbneFYWjOzvJSJgcLPLgc4DOT0laGyc/5qJtl2LMyx+sTsYtbKnIHKDWO1AHK1Qyau+GRgPSHdW/4OCM746ysN7RDo0TJfyp093q3pAucBQJYJBiNPKVs3je6U3L/dsDWTTNTLjZNUgyG3fAkEEyhPOLkZ/qGbCCktamJhZ5I76tI9VEBxGG2z+Tr+H+Tsm3SAW0NqKjSDS1gk8RM8N3SxAb5IuHXF7E4Qo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
