appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: SWNKkMY3R0YTQ2oWsvoFVZ1aw6S8fje3op7Y4Uy+hBhB8t1jtWKgDVd352k33glH/dO5EyG51dsDsldsbxXJ4dyd+nz3p8zGRbu+icbKc5feuQ4MG/VfYpV7xy/JknmmeLPzolVtiA/kHJlLx4eQ/xUUlZJKfYijonWvg594c1ZgVnfNKTRTP6HCSW3TQr+/Y8gYsua9OWyAsgMM1jIOjd925GJ2WymCfBQJ7lEfnnkjt0HuNLcwXVYZgF0aSRy1BvLYJpoHX5fozoP+ugHRGFNQcM7r1yFPPEkF/c634at300dVyyQm9S31/UTRwhImg0n5jx5iehv9WHeUgTsLdEtZvrK+vnJZPyy91DZZKJ+QnLUbk5OBVMPs+GKzJ/f0QWSPNk/QDimOZh27dVfNIQPb1uTURIjqqm18u5+ehLpkJsTnrRtO1elP/mUyX50WTZoAu0dLrXjHQoXicChfH51HdOCvwVMDXxRAiLZ943apCPoTBIor6/ARJRe8NcJuuAUzWNmDXeEC3KvyxljhFhnVz5hI3knGXGMGyx99BaTEZzjBzBT15M+aTzBjwCZtLTkSkE+vN9OCtk2RVxsYZ6EH1DOgL8zeIAc/ySZZh7vE88rqxc1Yfdp2yBiWqxi0KjBvQlQml7Sr45kMbeTPOm5ntkzyQmw0fAvBZIObiK0=}
