travis:
  secure:
    BINSTAR_TOKEN: QC+zbV7bkU4FRttdgWT4X3772J+yA5ztTH9gnjP68uGUAZo/eRvwDNxJExCxCj71x50xk/VhxPvq6sBSSyYQAxk0WJfwPx6jJNAbnJ4KAhjCQLGhXVll942AC7JQ+ff9utrK46rfxT0E3LzP5OzUrDyedmVnjOGd1idvMjyRR58KPRGpA9V5dJTnWuP8uPLSai1me9tr2S6wd+NaBwb/V9enf0/UJ2Fz5vr7zc/bQZE9bVWxK8suvFoR1zyUXhwQ9rIVZ4KFpjbIZ4joWmR9pS0fV1NrgTwCZb11JZKWClpEah1oEfAZ0tUN2U6UsXXg0fZ5ysTwCkr5N2g2JapEJvtp4M6p6ytOSh6vi2I5lFSRn1GnnElSBy1qvkwqcZwzr9fkZVaWMirEsWjXK5+sLxAYxj+gNzJ4et+y0CSf9K8viUt7zcGagkskHwwr++iHpuyM693b+q27jnG9Ufy7mYcX7kaP8ckkzBMAjwxoPw2gQyzsm5DxHGK1TEV9L91ych7Clr9Y7kZDbrQTrmfGk2MD50fcdpyPiexXSRF08+Z/rnRxjN/rbKc2KLN3EMnfDBuCtod92ob1tHkpTu9YcT3acJpdl8UFGcrwZ6nn06Ns+ezjeI9WbgEHBBasmIuDQn2tDZWJqUqMtxoKsJ+fi1Peb12Kfx30R9Qi8C4kvOg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
