travis:
  secure:
    BINSTAR_TOKEN: GGNVULROVc+y5eFMy7cHfCzmqdvZpgF8UafSrEN7oaC/+ZLuE7CGHxulXG9/oqyWaeZuT6lLIjpkzE3rlV/mSaEkbv4R2qTAiVX0p3iqNZHWGogpFB4r8tn6ETwcCrV8f8waIBh2Saoz3rexWdHxWcJfjylLPsPTn+ThFpB3uxpzKL9b2Mbk73hUaujcqRWc9rZnjkS07DgHAHUcc4AkULMKADvQYnGS9Qhm9PWABulCUP60EWlL+l8AVlS/GgIe2sp11RDqhDQTyXpDUx/FlQvGFNWtEv7bmjZEciudgCWtjtf10qQsmcdph5EK23T1YM+pZexTgJK28sWIr829UatK72Qda7SOQv4uksTwK/RAL/SL1nrqrX4pYgzmpwTspWea7YWDK518aXrBY/MLA9GuS7JWzZV3mESZeNBh+VUQIXuCfiC5bQ0vbNMTNc01tkt0lASVqwei1EtKG9ZpnFK6FtoCbotS/Ypdt4z75I/CgoPyBLHOwGRFrT36moVNKcIwBsRHJhLN/cDEeGJMA363NrJBV2ohxTin1zkU0vT1eScfLVvd/q+2FlzW+O8U5Il9axL9A9Dh3mGnjYVyyRDFAAJ+GGG8ff0FIX08V+H7YzFUyErYIrN84Tni4K68f3qVB8Kaz/JkLdRW7E6527BPh49wCIgDZUFlhSZlT+s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
